package com.cricket.scorecard.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

/**
 * Aggregate Root Domain Document representing a single-innings Cricket Match state.
 * 
 * DEVELOPER NOTES & ANNOTATIONS:
 * - @Document(collection = "matches"): Maps this object to the 'matches' collection in MongoDB.
 * - Single Document Pattern: All live scorecard attributes (runs, wickets, overs, current striker,
 *   and ball history) are aggregated into this single document to ensure fast atomic reads and updates
 *   without complex database joins.
 */
@Document(collection = "matches")
public class Match {

    /**
     * Unique identifier generated by MongoDB for the match record.
     */
    @Id
    private String id;

    // Name or code of the batting team (e.g. "IND")
    private String battingTeam;

    // Name or code of the bowling team (e.g. "AUS")
    private String bowlingTeam;

    // Maximum total overs allocated for this single innings (e.g. 20 overs)
    private int totalOvers;

    // Running cumulative score of runs scored by the batting team
    private int totalRuns = 0;

    // Running cumulative count of wickets lost by the batting team
    private int totalWickets = 0;

    // Formatted overs count (e.g. 0.1, 0.5, 1.0, 5.4)
    private double oversBowled = 0.0;

    // Total count of valid legal deliveries bowled so far (excludes Wides and No-Balls)
    private int validBalls = 0;

    // Current status of the match: "LIVE" (in progress) or "COMPLETED" (finished)
    private String status = "LIVE";

    // Player ID of the batsman currently facing the delivery (on strike)
    private String strikerId;

    // Player ID of the non-facing batsman at the bowler's end
    private String nonStrikerId;

    // Embedded list tracking ball-by-ball delivery events recorded in this match
    private List<BallEvent> recentBalls = new ArrayList<>();

    /**
     * Default No-Args Constructor required by Spring Data MongoDB and Jackson.
     */
    public Match() {
    }

    /**
     * Constructor for initializing a new Match instance.
     * 
     * @param id           Match document ID.
     * @param battingTeam  Batting team name.
     * @param bowlingTeam  Bowling team name.
     * @param totalOvers   Total overs limit.
     * @param strikerId    Initial striker player ID.
     * @param nonStrikerId Initial non-striker player ID.
     */
    public Match(String id, String battingTeam, String bowlingTeam, int totalOvers, String strikerId, String nonStrikerId) {
        this.id = id;
        this.battingTeam = battingTeam;
        this.bowlingTeam = bowlingTeam;
        this.totalOvers = totalOvers;
        this.strikerId = strikerId;
        this.nonStrikerId = nonStrikerId;
    }

    // --- Standard Getters & Setters ---

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getBattingTeam() {
        return battingTeam;
    }

    public void setBattingTeam(String battingTeam) {
        this.battingTeam = battingTeam;
    }

    public String getBowlingTeam() {
        return bowlingTeam;
    }

    public void setBowlingTeam(String bowlingTeam) {
        this.bowlingTeam = bowlingTeam;
    }

    public int getTotalOvers() {
        return totalOvers;
    }

    public void setTotalOvers(int totalOvers) {
        this.totalOvers = totalOvers;
    }

    public int getTotalRuns() {
        return totalRuns;
    }

    public void setTotalRuns(int totalRuns) {
        this.totalRuns = totalRuns;
    }

    public int getTotalWickets() {
        return totalWickets;
    }

    public void setTotalWickets(int totalWickets) {
        this.totalWickets = totalWickets;
    }

    public double getOversBowled() {
        return oversBowled;
    }

    public void setOversBowled(double oversBowled) {
        this.oversBowled = oversBowled;
    }

    public int getValidBalls() {
        return validBalls;
    }

    public void setValidBalls(int validBalls) {
        this.validBalls = validBalls;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStrikerId() {
        return strikerId;
    }

    public void setStrikerId(String strikerId) {
        this.strikerId = strikerId;
    }

    public String getNonStrikerId() {
        return nonStrikerId;
    }

    public void setNonStrikerId(String nonStrikerId) {
        this.nonStrikerId = nonStrikerId;
    }

    public List<BallEvent> getRecentBalls() {
        return recentBalls;
    }

    public void setRecentBalls(List<BallEvent> recentBalls) {
        this.recentBalls = recentBalls;
    }
}

